import type { Recipe } from "../types";

/**
 * A small, hand-checked recipe library. Every entry has real quantities and real
 * steps, so a household can cook straight from the screen. The ranker prefers
 * these over anything generated; AI recipes are only a fallback and are labelled.
 *
 * `containsAllergens` must list every allergen present anywhere in the recipe --
 * it is the input to a hard exclusion, so under-listing is a safety bug.
 */
export const RECIPE_LIBRARY: Recipe[] = [
  {
    id: "lib-palak-paneer",
    title: "Blended Palak Paneer",
    cuisine: "Indian",
    totalMinutes: 30,
    difficulty: "easy",
    heatLevel: "mild",
    form: "curry",
    servesAdults: 4,
    produceUsed: [
      { name: "spinach", amount: "10 oz (280 g), about 1 large bag" },
      { name: "cilantro", amount: "1/2 cup leaves and tender stems" },
      { name: "garlic", amount: "3 cloves" },
    ],
    otherIngredients: [
      { name: "paneer", amount: "8 oz (225 g), cubed", pantry: false },
      { name: "heavy cream or coconut cream", amount: "1/4 cup", pantry: false },
      { name: "onion", amount: "1 small", pantry: true },
      { name: "ginger", amount: "1 inch piece", pantry: true },
      { name: "ground cumin", amount: "1 tsp", pantry: true },
      { name: "ground coriander", amount: "1 tsp", pantry: true },
      { name: "garam masala", amount: "1/2 tsp", pantry: true },
      { name: "neutral oil", amount: "2 tbsp", pantry: true },
      { name: "salt", amount: "to taste", pantry: true },
      { name: "rice", amount: "for 4, to serve", pantry: true },
    ],
    steps: [
      "Bring a large pot of water to a boil. Add the spinach and cook for 60 seconds, then drain and rinse under cold water to keep the colour bright.",
      "Squeeze the spinach dry and blend it with the cilantro, garlic, ginger and 2 tbsp water until completely smooth. Blending means no leafy strands and no visible onion later.",
      "Heat the oil in a wide pan over medium. Add the finely chopped onion and cook 5 minutes until soft and golden.",
      "Stir in the cumin, coriander and garam masala and cook 30 seconds until fragrant.",
      "Add the spinach purée and 1/4 cup water. Simmer 6-8 minutes, stirring, until it thickens and darkens slightly.",
      "Stir in the cream and season with salt. Add the paneer cubes and warm through for 3 minutes -- do not boil hard, or the paneer toughens.",
      "Serve with rice.",
    ],
    texturePreferences: ["veg-blended-into-sauces", "no-visible-onions", "sauce-on-the-side"],
    dietaryTags: ["vegetarian", "gluten-free"],
    containsAllergens: ["dairy"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-veggie-quesadillas",
    title: "Zucchini & Carrot Quesadillas",
    cuisine: "Mexican",
    totalMinutes: 20,
    difficulty: "easy",
    heatLevel: "none",
    form: "handheld",
    servesAdults: 4,
    produceUsed: [
      { name: "zucchini", amount: "2 medium, coarsely grated" },
      { name: "carrots", amount: "2 large, coarsely grated" },
      { name: "cilantro", amount: "1/3 cup, chopped" },
    ],
    otherIngredients: [
      { name: "flour tortillas", amount: "8 medium", pantry: false },
      { name: "sharp cheddar or Monterey Jack", amount: "2 cups grated", pantry: false },
      { name: "lime", amount: "1", pantry: false },
      { name: "ground cumin", amount: "1 tsp", pantry: true },
      { name: "garlic", amount: "2 cloves, grated", pantry: true },
      { name: "olive oil", amount: "2 tbsp", pantry: true },
      { name: "salt", amount: "1/2 tsp", pantry: true },
      { name: "sour cream", amount: "1/2 cup, to serve", pantry: false },
    ],
    steps: [
      "Toss the grated zucchini with 1/2 tsp salt and leave 5 minutes, then squeeze out the liquid firmly in a clean towel. This is what stops a soggy quesadilla.",
      "Heat the oil in a large skillet over medium-high. Add the carrot and cook 3 minutes, then the zucchini, garlic and cumin. Cook 3 more minutes until dry and lightly browned.",
      "Stir in the cilantro and a squeeze of lime. Tip into a bowl and wipe the pan.",
      "Lay a tortilla in the dry pan over medium. Scatter over cheese, a quarter of the vegetables, then more cheese and a second tortilla.",
      "Cook 2-3 minutes a side, pressing gently, until crisp and the cheese has melted. Repeat for the rest.",
      "Cut into wedges and serve with sour cream on the side.",
    ],
    texturePreferences: ["no-visible-onions", "finger-food", "sauce-on-the-side", "veg-blended-into-sauces"],
    dietaryTags: ["vegetarian"],
    containsAllergens: ["dairy", "gluten", "wheat"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-carrot-zucchini-traybake",
    title: "Roasted Carrot & Zucchini Tray with Herby Yogurt",
    cuisine: "Mediterranean",
    totalMinutes: 35,
    difficulty: "easy",
    heatLevel: "none",
    form: "traybake",
    servesAdults: 4,
    produceUsed: [
      { name: "carrots", amount: "1 lb (450 g), cut into batons" },
      { name: "zucchini", amount: "2 medium, cut into thick half-moons" },
      { name: "cilantro", amount: "1/2 cup, chopped" },
    ],
    otherIngredients: [
      { name: "plain yogurt", amount: "1 cup", pantry: false },
      { name: "chickpeas", amount: "1 can (15 oz), drained", pantry: true },
      { name: "lemon", amount: "1", pantry: false },
      { name: "olive oil", amount: "3 tbsp", pantry: true },
      { name: "ground cumin", amount: "2 tsp", pantry: true },
      { name: "garlic", amount: "2 cloves", pantry: true },
      { name: "salt and pepper", amount: "to taste", pantry: true },
      { name: "rice", amount: "for 4, to serve", pantry: true },
    ],
    steps: [
      "Heat the oven to 425F (220C).",
      "Put the carrots on a large sheet pan with 2 tbsp oil, the cumin, salt and pepper. Roast 12 minutes -- carrots get a head start because they are denser.",
      "Add the zucchini and the drained chickpeas, toss, and roast another 15 minutes until everything is browned at the edges. Roasting, not steaming, is what gives the sweetness here.",
      "Meanwhile stir the yogurt with the grated garlic, half the cilantro, a squeeze of lemon and a pinch of salt.",
      "Scatter the remaining cilantro over the tray and serve with rice and the herby yogurt in a bowl alongside, so everyone adds their own.",
    ],
    texturePreferences: ["roasted-not-steamed", "sauce-on-the-side", "no-visible-onions", "no-mixed-textures"],
    dietaryTags: ["vegetarian", "gluten-free"],
    containsAllergens: ["dairy"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-thai-carrot-soup",
    title: "Thai Coconut Carrot Soup",
    cuisine: "Thai",
    totalMinutes: 30,
    difficulty: "easy",
    heatLevel: "mild",
    form: "soup",
    servesAdults: 4,
    produceUsed: [
      { name: "carrots", amount: "1.5 lb (680 g), roughly chopped" },
      { name: "cilantro", amount: "1/2 cup, plus stems" },
      { name: "ginger", amount: "1.5 inch piece" },
    ],
    otherIngredients: [
      { name: "coconut milk", amount: "1 can (14 oz)", pantry: true },
      { name: "vegetable stock", amount: "3 cups", pantry: true },
      { name: "red curry paste", amount: "1 tbsp (mild)", pantry: false },
      { name: "lime", amount: "1", pantry: false },
      { name: "onion", amount: "1", pantry: true },
      { name: "neutral oil", amount: "1 tbsp", pantry: true },
      { name: "salt", amount: "to taste", pantry: true },
    ],
    steps: [
      "Soften the chopped onion and ginger in the oil over medium heat for 5 minutes.",
      "Stir in the curry paste and cook 1 minute until it smells fragrant.",
      "Add the carrots, the cilantro stems and the stock. Simmer 18 minutes, until a knife slides through a carrot with no resistance.",
      "Blend until completely smooth, then return to the pan and stir in the coconut milk. Warm through -- do not boil.",
      "Season with salt and lime juice. Top with the cilantro leaves.",
      "For a milder bowl, hold back half the curry paste and stir it into the adults' portions at the table.",
    ],
    texturePreferences: ["veg-blended-into-sauces", "no-visible-onions"],
    dietaryTags: ["dairy-free"],
    containsAllergens: ["shellfish", "fish"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe. Most red curry pastes contain shrimp paste and fish sauce -- check the jar if that matters to you.",
  },
  {
    id: "lib-spinach-ricotta-bake",
    title: "Spinach & Ricotta Pasta Bake",
    cuisine: "Italian",
    totalMinutes: 45,
    difficulty: "easy",
    heatLevel: "none",
    form: "bake",
    servesAdults: 4,
    produceUsed: [
      { name: "spinach", amount: "10 oz (280 g)" },
      { name: "garlic", amount: "3 cloves" },
    ],
    otherIngredients: [
      { name: "rigatoni or penne", amount: "12 oz (340 g)", pantry: true },
      { name: "ricotta", amount: "15 oz (425 g)", pantry: false },
      { name: "mozzarella", amount: "1.5 cups grated", pantry: false },
      { name: "parmesan", amount: "1/2 cup grated", pantry: false },
      { name: "canned crushed tomatoes", amount: "1 can (28 oz)", pantry: true },
      { name: "olive oil", amount: "2 tbsp", pantry: true },
      { name: "dried oregano", amount: "1 tsp", pantry: true },
      { name: "salt and pepper", amount: "to taste", pantry: true },
    ],
    steps: [
      "Heat the oven to 400F (200C). Boil the pasta 2 minutes short of the package time and drain.",
      "Wilt the spinach in a dry pan over medium heat, 2-3 minutes. Cool slightly, squeeze out the water, and chop finely.",
      "Warm the oil with the sliced garlic and oregano for 1 minute, add the tomatoes, and simmer 10 minutes. Season.",
      "Mix the ricotta with the chopped spinach, the parmesan, salt and pepper.",
      "Combine the pasta with the tomato sauce in a baking dish, dot spoonfuls of the spinach ricotta through it, and top with the mozzarella.",
      "Bake 20 minutes until bubbling and browned on top. Rest 5 minutes before serving.",
    ],
    texturePreferences: ["no-visible-onions", "veg-blended-into-sauces"],
    dietaryTags: ["vegetarian"],
    containsAllergens: ["dairy", "gluten", "wheat"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-mushroom-pappardelle",
    title: "Creamy Mushroom Pappardelle",
    cuisine: "Italian",
    totalMinutes: 25,
    difficulty: "easy",
    heatLevel: "none",
    form: "pasta",
    servesAdults: 4,
    produceUsed: [
      { name: "mushrooms", amount: "1 lb (450 g), sliced thick" },
      { name: "parsley", amount: "1/3 cup, chopped" },
      { name: "garlic", amount: "3 cloves" },
    ],
    otherIngredients: [
      { name: "pappardelle or tagliatelle", amount: "12 oz (340 g)", pantry: true },
      { name: "heavy cream", amount: "3/4 cup", pantry: false },
      { name: "parmesan", amount: "3/4 cup grated", pantry: false },
      { name: "butter", amount: "2 tbsp", pantry: false },
      { name: "olive oil", amount: "1 tbsp", pantry: true },
      { name: "dried thyme", amount: "1 tsp", pantry: true },
      { name: "salt and pepper", amount: "to taste", pantry: true },
    ],
    steps: [
      "Put the pasta water on to boil and salt it well.",
      "Heat the oil and butter in a wide pan over high heat. Add the mushrooms in a single layer and leave them undisturbed for 4 minutes so they brown rather than steam.",
      "Stir, add the garlic and thyme, and cook 3 more minutes until deeply golden.",
      "Cook the pasta. Reserve 1 cup of the water before draining.",
      "Lower the heat, add the cream and half the parmesan to the mushrooms, then the drained pasta and a splash of the pasta water. Toss until the sauce coats every strand.",
      "Finish with the parsley, the rest of the parmesan and plenty of black pepper.",
    ],
    texturePreferences: ["no-visible-onions"],
    dietaryTags: ["vegetarian"],
    containsAllergens: ["dairy", "gluten", "wheat"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-chana-saag",
    title: "Chana Saag (Chickpea & Spinach Curry)",
    cuisine: "Indian",
    totalMinutes: 30,
    difficulty: "easy",
    heatLevel: "mild",
    form: "curry",
    servesAdults: 4,
    produceUsed: [
      { name: "spinach", amount: "8 oz (225 g)" },
      { name: "cilantro", amount: "1/3 cup" },
      { name: "garlic", amount: "3 cloves" },
    ],
    otherIngredients: [
      { name: "chickpeas", amount: "2 cans (15 oz each), drained", pantry: true },
      { name: "canned chopped tomatoes", amount: "1 can (14 oz)", pantry: true },
      { name: "coconut milk", amount: "1/2 cup", pantry: true },
      { name: "onion", amount: "1", pantry: true },
      { name: "ginger", amount: "1 inch", pantry: true },
      { name: "ground cumin", amount: "2 tsp", pantry: true },
      { name: "ground turmeric", amount: "1/2 tsp", pantry: true },
      { name: "garam masala", amount: "1 tsp", pantry: true },
      { name: "neutral oil", amount: "2 tbsp", pantry: true },
      { name: "rice", amount: "for 4, to serve", pantry: true },
    ],
    steps: [
      "Blend the onion, garlic and ginger to a paste with 2 tbsp water.",
      "Heat the oil over medium and fry the paste for 6 minutes, stirring, until it no longer smells raw and has darkened.",
      "Add the cumin, turmeric and garam masala, cook 30 seconds, then the tomatoes. Simmer 5 minutes.",
      "Stir in the chickpeas and coconut milk and simmer 8 minutes.",
      "Add the spinach a handful at a time, letting each wilt before the next. Cook 2 more minutes.",
      "Stir through the cilantro, season, and serve over rice.",
    ],
    texturePreferences: ["veg-blended-into-sauces", "no-visible-onions"],
    dietaryTags: ["vegetarian", "vegan", "gluten-free", "dairy-free"],
    containsAllergens: [],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-zucchini-fritters",
    title: "Zucchini & Carrot Fritters",
    cuisine: "Mediterranean",
    totalMinutes: 25,
    difficulty: "easy",
    heatLevel: "none",
    form: "handheld",
    servesAdults: 4,
    produceUsed: [
      { name: "zucchini", amount: "3 medium (about 1.25 lb), grated" },
      { name: "carrots", amount: "2 medium, grated" },
      { name: "cilantro", amount: "1/3 cup, chopped" },
    ],
    otherIngredients: [
      { name: "eggs", amount: "2", pantry: false },
      { name: "all-purpose flour", amount: "2/3 cup", pantry: true },
      { name: "feta", amount: "4 oz (110 g), crumbled", pantry: false },
      { name: "plain yogurt", amount: "1/2 cup, to serve", pantry: false },
      { name: "lemon", amount: "1", pantry: false },
      { name: "olive oil", amount: "for frying", pantry: true },
      { name: "salt and pepper", amount: "to taste", pantry: true },
    ],
    steps: [
      "Toss the grated zucchini with 1 tsp salt and leave 10 minutes. Squeeze it very dry in a clean towel -- this step decides whether the fritters hold together.",
      "Mix the zucchini and carrot with the eggs, flour, feta, cilantro and plenty of pepper.",
      "Heat a shallow layer of oil in a skillet over medium-high. Drop in heaped tablespoons and flatten gently.",
      "Fry 3 minutes a side until deep golden and crisp. Drain on paper towel and salt lightly.",
      "Serve with yogurt and lemon on the side for dipping.",
    ],
    texturePreferences: ["finger-food", "no-visible-onions", "sauce-on-the-side", "veg-blended-into-sauces"],
    dietaryTags: ["vegetarian"],
    containsAllergens: ["dairy", "egg", "gluten", "wheat"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-thai-green-curry",
    title: "Thai Green Curry with Zucchini",
    cuisine: "Thai",
    totalMinutes: 30,
    difficulty: "easy",
    heatLevel: "medium",
    form: "curry",
    servesAdults: 4,
    produceUsed: [
      { name: "zucchini", amount: "2 medium, sliced" },
      { name: "carrots", amount: "2, thinly sliced" },
      { name: "green beans", amount: "6 oz (170 g)" },
      { name: "cilantro", amount: "1/3 cup" },
    ],
    otherIngredients: [
      { name: "green curry paste", amount: "3 tbsp", pantry: false },
      { name: "coconut milk", amount: "2 cans (14 oz each)", pantry: true },
      { name: "firm tofu or chicken thigh", amount: "1 lb (450 g)", pantry: false },
      { name: "soy sauce", amount: "2 tbsp", pantry: true },
      { name: "brown sugar", amount: "1 tsp", pantry: true },
      { name: "lime", amount: "1", pantry: false },
      { name: "jasmine rice", amount: "for 4, to serve", pantry: true },
    ],
    steps: [
      "Spoon the thick cream from the top of one can of coconut milk into a wide pan. Heat until it splits and looks oily.",
      "Add the curry paste and fry 2 minutes -- this is what develops the flavour rather than leaving it sharp.",
      "Add the rest of the coconut milk, the soy sauce and the sugar. Bring to a simmer.",
      "Add the tofu or chicken and the carrots. Simmer 8 minutes.",
      "Add the zucchini and green beans and cook 5 minutes more, until just tender.",
      "Finish with lime juice and cilantro. Serve with jasmine rice.",
    ],
    texturePreferences: ["sauce-on-the-side", "no-visible-onions"],
    dietaryTags: ["dairy-free"],
    containsAllergens: ["soy", "gluten", "wheat", "shellfish", "fish"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe. Most green curry pastes contain shrimp paste and fish sauce -- check the jar if that matters to you.",
  },
  {
    id: "lib-mexican-rice-bowl",
    title: "Charred Zucchini & Black Bean Rice Bowls",
    cuisine: "Mexican",
    totalMinutes: 30,
    difficulty: "easy",
    heatLevel: "mild",
    form: "rice-bowl",
    servesAdults: 4,
    produceUsed: [
      { name: "zucchini", amount: "3 medium, cut into half-moons" },
      { name: "carrots", amount: "2, grated" },
      { name: "cilantro", amount: "3/4 cup" },
    ],
    otherIngredients: [
      { name: "black beans", amount: "2 cans (15 oz each), drained", pantry: true },
      { name: "long-grain rice", amount: "1.5 cups uncooked", pantry: true },
      { name: "lime", amount: "2", pantry: false },
      { name: "cheddar or cotija", amount: "1 cup grated", pantry: false },
      { name: "ground cumin", amount: "2 tsp", pantry: true },
      { name: "smoked paprika", amount: "1 tsp", pantry: true },
      { name: "garlic", amount: "2 cloves", pantry: true },
      { name: "olive oil", amount: "3 tbsp", pantry: true },
      { name: "sour cream", amount: "1/2 cup, to serve", pantry: false },
    ],
    steps: [
      "Cook the rice. When it is done, fork through the juice of 1 lime and half the cilantro.",
      "Get a skillet very hot. Toss the zucchini with 2 tbsp oil, the cumin and paprika, and cook in a single layer for 4 minutes without stirring, so it chars rather than stews. Turn and cook 3 minutes more.",
      "Warm the black beans with the grated garlic, 1 tbsp oil and a splash of water. Season well.",
      "Build bowls with the lime rice, beans, charred zucchini and raw grated carrot.",
      "Put the cheese, sour cream, remaining cilantro and lime wedges on the table so everyone assembles their own bowl.",
    ],
    texturePreferences: ["no-mixed-textures", "sauce-on-the-side", "no-visible-onions", "roasted-not-steamed"],
    dietaryTags: ["vegetarian", "gluten-free"],
    containsAllergens: ["dairy"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-minestrone",
    title: "Quick Vegetable Minestrone",
    cuisine: "Italian",
    totalMinutes: 35,
    difficulty: "easy",
    heatLevel: "none",
    form: "soup",
    servesAdults: 4,
    produceUsed: [
      { name: "carrots", amount: "3, diced" },
      { name: "zucchini", amount: "2, diced" },
      { name: "spinach", amount: "5 oz (140 g)" },
      { name: "celery", amount: "2 stalks" },
    ],
    otherIngredients: [
      { name: "cannellini beans", amount: "1 can (15 oz)", pantry: true },
      { name: "small pasta", amount: "1 cup", pantry: true },
      { name: "canned chopped tomatoes", amount: "1 can (14 oz)", pantry: true },
      { name: "vegetable stock", amount: "6 cups", pantry: true },
      { name: "parmesan", amount: "to serve", pantry: false },
      { name: "olive oil", amount: "3 tbsp", pantry: true },
      { name: "garlic", amount: "3 cloves", pantry: true },
      { name: "dried oregano", amount: "1 tsp", pantry: true },
    ],
    steps: [
      "Cook the carrot and celery in the oil over medium heat for 8 minutes, until soft and sweet.",
      "Add the garlic and oregano, cook 1 minute, then the tomatoes and stock. Simmer 10 minutes.",
      "Add the pasta and beans and cook until the pasta is done, about 9 minutes.",
      "Stir in the zucchini for the last 4 minutes and the spinach for the last 1 minute.",
      "Season generously and serve with parmesan and a drizzle of olive oil.",
    ],
    texturePreferences: ["no-visible-onions"],
    dietaryTags: ["vegetarian"],
    containsAllergens: ["dairy", "gluten", "wheat"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-aloo-gobi",
    title: "Roasted Aloo Gobi",
    cuisine: "Indian",
    totalMinutes: 40,
    difficulty: "easy",
    heatLevel: "mild",
    form: "traybake",
    servesAdults: 4,
    produceUsed: [
      { name: "cauliflower", amount: "1 large head, in florets" },
      { name: "potatoes", amount: "1 lb (450 g), in chunks" },
      { name: "cilantro", amount: "1/2 cup" },
    ],
    otherIngredients: [
      { name: "ground turmeric", amount: "1 tsp", pantry: true },
      { name: "ground cumin", amount: "2 tsp", pantry: true },
      { name: "ground coriander", amount: "2 tsp", pantry: true },
      { name: "garam masala", amount: "1 tsp", pantry: true },
      { name: "garlic", amount: "4 cloves", pantry: true },
      { name: "ginger", amount: "1 inch", pantry: true },
      { name: "neutral oil", amount: "4 tbsp", pantry: true },
      { name: "lemon", amount: "1", pantry: false },
      { name: "rice", amount: "for 4, to serve", pantry: true },
    ],
    steps: [
      "Heat the oven to 450F (230C) with a large sheet pan inside.",
      "Toss the potatoes with half the oil and half the spices. Spread on the hot pan and roast 15 minutes.",
      "Toss the cauliflower with the remaining oil, spices, grated garlic and ginger.",
      "Add it to the pan, turn everything, and roast 20 minutes more until the cauliflower edges are dark and crisp. Roasting gives a much better texture than the usual steamy pan version.",
      "Squeeze over lemon, scatter with cilantro and serve with rice.",
    ],
    texturePreferences: ["roasted-not-steamed", "no-visible-onions", "no-mixed-textures", "finger-food"],
    dietaryTags: ["vegetarian", "vegan", "gluten-free", "dairy-free"],
    containsAllergens: [],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-pad-see-ew",
    title: "Pad See Ew with Broccoli & Carrot",
    cuisine: "Thai",
    totalMinutes: 25,
    difficulty: "medium",
    heatLevel: "none",
    form: "stir-fry",
    servesAdults: 4,
    produceUsed: [
      { name: "broccoli", amount: "1 large head, in small florets" },
      { name: "carrots", amount: "2, thinly sliced" },
    ],
    otherIngredients: [
      { name: "wide rice noodles", amount: "14 oz (400 g) fresh, or 8 oz dried", pantry: false },
      { name: "eggs", amount: "3", pantry: false },
      { name: "dark soy sauce", amount: "2 tbsp", pantry: true },
      { name: "light soy sauce", amount: "2 tbsp", pantry: true },
      { name: "oyster sauce", amount: "2 tbsp", pantry: false },
      { name: "sugar", amount: "1 tsp", pantry: true },
      { name: "garlic", amount: "4 cloves", pantry: true },
      { name: "neutral oil", amount: "3 tbsp", pantry: true },
    ],
    steps: [
      "Soak dried noodles per the package, or loosen fresh ones under warm water. Drain well.",
      "Mix the soy sauces, oyster sauce and sugar in a small bowl.",
      "Get a wok or large skillet smoking hot. Add 1 tbsp oil and the garlic, then the broccoli and carrot. Stir-fry 3 minutes with a splash of water, then tip onto a plate.",
      "Add the remaining oil, then the noodles. Leave them 1 minute to catch and char slightly -- that smoky edge is the whole point of the dish.",
      "Push the noodles aside, scramble the eggs in the space, then toss everything together with the sauce and the vegetables.",
      "Serve immediately.",
    ],
    texturePreferences: ["no-visible-onions"],
    dietaryTags: ["dairy-free"],
    containsAllergens: ["egg", "soy", "shellfish", "gluten", "wheat"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-shakshuka",
    title: "Spinach Shakshuka",
    cuisine: "Middle Eastern",
    totalMinutes: 30,
    difficulty: "easy",
    heatLevel: "mild",
    form: "braise",
    servesAdults: 4,
    produceUsed: [
      { name: "spinach", amount: "7 oz (200 g)" },
      { name: "bell pepper", amount: "2, sliced" },
      { name: "cilantro", amount: "1/3 cup" },
    ],
    otherIngredients: [
      { name: "eggs", amount: "6", pantry: false },
      { name: "canned chopped tomatoes", amount: "1 can (28 oz)", pantry: true },
      { name: "feta", amount: "4 oz (110 g)", pantry: false },
      { name: "ground cumin", amount: "2 tsp", pantry: true },
      { name: "smoked paprika", amount: "1 tsp", pantry: true },
      { name: "garlic", amount: "3 cloves", pantry: true },
      { name: "olive oil", amount: "3 tbsp", pantry: true },
      { name: "crusty bread", amount: "1 loaf, to serve", pantry: true },
    ],
    steps: [
      "Cook the peppers in the oil over medium heat for 8 minutes until soft.",
      "Add the garlic, cumin and paprika, cook 1 minute, then the tomatoes. Simmer 10 minutes until thick enough to hold a trail when you drag a spoon through it.",
      "Stir in the spinach and let it wilt.",
      "Make six wells and crack an egg into each. Cover and cook 6-8 minutes, until the whites are set and the yolks still soft.",
      "Crumble over the feta, scatter with cilantro, and serve straight from the pan with bread.",
    ],
    texturePreferences: ["no-visible-onions", "sauce-on-the-side"],
    dietaryTags: ["vegetarian"],
    containsAllergens: ["dairy", "egg", "gluten", "wheat"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-mushroom-ragu-polenta",
    title: "Mushroom Ragù over Soft Polenta",
    cuisine: "Italian",
    totalMinutes: 40,
    difficulty: "medium",
    heatLevel: "none",
    form: "braise",
    servesAdults: 4,
    produceUsed: [
      { name: "mushrooms", amount: "1.25 lb (560 g), roughly torn" },
      { name: "carrots", amount: "2, finely diced" },
      { name: "parsley", amount: "1/3 cup" },
    ],
    otherIngredients: [
      { name: "polenta", amount: "1 cup", pantry: true },
      { name: "parmesan", amount: "1 cup grated", pantry: false },
      { name: "butter", amount: "3 tbsp", pantry: false },
      { name: "canned chopped tomatoes", amount: "1 can (14 oz)", pantry: true },
      { name: "vegetable stock", amount: "4 cups", pantry: true },
      { name: "garlic", amount: "3 cloves", pantry: true },
      { name: "dried thyme", amount: "1 tsp", pantry: true },
      { name: "olive oil", amount: "3 tbsp", pantry: true },
    ],
    steps: [
      "Brown the mushrooms in the oil over high heat in two batches, 5 minutes each, leaving them alone so they colour. Crowding the pan makes them grey and watery.",
      "Return all the mushrooms, add the carrot, garlic and thyme, and cook 5 minutes.",
      "Add the tomatoes and 1 cup of the stock. Simmer 20 minutes until thick and glossy.",
      "Meanwhile whisk the polenta into the remaining 3 cups of simmering salted stock. Cook 15 minutes, whisking often, then beat in the butter and parmesan.",
      "Spoon the polenta into bowls, top with the ragù and the parsley.",
    ],
    texturePreferences: ["veg-blended-into-sauces", "no-visible-onions"],
    dietaryTags: ["vegetarian", "gluten-free"],
    containsAllergens: ["dairy"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-sheet-pan-fajitas",
    title: "Sheet-Pan Chicken Fajitas",
    cuisine: "Mexican",
    totalMinutes: 30,
    difficulty: "easy",
    heatLevel: "mild",
    form: "traybake",
    servesAdults: 4,
    produceUsed: [
      { name: "bell pepper", amount: "3, sliced" },
      { name: "zucchini", amount: "2, in thick sticks" },
      { name: "cilantro", amount: "1/2 cup" },
    ],
    otherIngredients: [
      { name: "chicken thighs", amount: "1.5 lb (680 g), sliced", pantry: false },
      { name: "flour tortillas", amount: "8", pantry: false },
      { name: "onion", amount: "1 large", pantry: true },
      { name: "lime", amount: "2", pantry: false },
      { name: "ground cumin", amount: "2 tsp", pantry: true },
      { name: "smoked paprika", amount: "2 tsp", pantry: true },
      { name: "garlic powder", amount: "1 tsp", pantry: true },
      { name: "olive oil", amount: "3 tbsp", pantry: true },
      { name: "sour cream", amount: "1/2 cup, to serve", pantry: false },
    ],
    steps: [
      "Heat the oven to 450F (230C).",
      "Toss the chicken, peppers, zucchini and onion with the oil, cumin, paprika, garlic powder and 1 tsp salt.",
      "Spread over two sheet pans -- one crowded pan steams instead of roasting.",
      "Roast 20 minutes, turning once, until the chicken is cooked through to 165F (74C) and the edges are charred.",
      "Squeeze over lime, scatter with cilantro, and serve with warm tortillas and sour cream so everyone builds their own.",
    ],
    texturePreferences: ["roasted-not-steamed", "finger-food", "sauce-on-the-side"],
    dietaryTags: ["dairy-free-option"],
    containsAllergens: ["gluten", "wheat", "dairy"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-carrot-peanut-noodles",
    title: "Crunchy Carrot & Peanut Noodle Bowls",
    cuisine: "Thai",
    totalMinutes: 20,
    difficulty: "easy",
    heatLevel: "mild",
    form: "salad",
    servesAdults: 4,
    produceUsed: [
      { name: "carrots", amount: "1 lb (450 g), julienned or coarsely grated" },
      { name: "cabbage", amount: "1/4 head, finely shredded" },
      { name: "cilantro", amount: "1 cup, roughly chopped" },
    ],
    otherIngredients: [
      { name: "rice noodles", amount: "10 oz (280 g)", pantry: false },
      { name: "shelled edamame", amount: "1.5 cups, from frozen", pantry: false },
      { name: "roasted peanuts", amount: "2/3 cup, chopped", pantry: false },
      { name: "peanut butter", amount: "3 tbsp", pantry: false },
      { name: "lime", amount: "2", pantry: false },
      { name: "soy sauce", amount: "3 tbsp", pantry: true },
      { name: "brown sugar", amount: "1 tbsp", pantry: true },
      { name: "ginger", amount: "1 inch, grated", pantry: true },
      { name: "neutral oil", amount: "2 tbsp", pantry: true },
    ],
    steps: [
      "Soak or boil the rice noodles per the package, adding the edamame for the last minute. Drain and rinse under cold water so they stop cooking and don't clump.",
      "Whisk the peanut butter, soy sauce, sugar, ginger, oil and the juice of both limes with 3 tbsp warm water until it pours smoothly. Add more water a teaspoon at a time if it seizes.",
      "Toss the noodles and edamame with two-thirds of the dressing, then fold through the carrot and cabbage.",
      "Pile into bowls, spoon over the rest of the dressing, and top with the cilantro and peanuts.",
      "Good warm or cold, and it keeps well for lunch the next day.",
    ],
    texturePreferences: ["no-visible-onions", "no-mixed-textures", "sauce-on-the-side"],
    dietaryTags: ["vegetarian", "vegan", "dairy-free"],
    containsAllergens: ["peanut", "soy", "gluten", "wheat"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-spinach-dal",
    title: "Spinach Tarka Dal",
    cuisine: "Indian",
    totalMinutes: 35,
    difficulty: "easy",
    heatLevel: "mild",
    form: "curry",
    servesAdults: 4,
    produceUsed: [
      { name: "spinach", amount: "7 oz (200 g)" },
      { name: "cilantro", amount: "1/2 cup" },
      { name: "carrots", amount: "2, finely diced" },
    ],
    otherIngredients: [
      { name: "red lentils", amount: "1.5 cups", pantry: true },
      { name: "ground turmeric", amount: "1 tsp", pantry: true },
      { name: "cumin seeds", amount: "1.5 tsp", pantry: true },
      { name: "garlic", amount: "4 cloves, sliced", pantry: true },
      { name: "ginger", amount: "1 inch", pantry: true },
      { name: "butter or ghee", amount: "3 tbsp", pantry: false },
      { name: "lemon", amount: "1", pantry: false },
      { name: "rice", amount: "for 4, to serve", pantry: true },
    ],
    steps: [
      "Rinse the lentils until the water runs clear. Simmer with the turmeric, grated ginger, diced carrot and 5 cups water for 20 minutes, until collapsed and creamy.",
      "Stir in the spinach and let it wilt. Season well with salt.",
      "For the tarka, melt the butter in a small pan, add the cumin seeds and sliced garlic, and fry until the garlic is pale gold -- about 90 seconds. Watch it; it burns fast.",
      "Pour the sizzling tarka over the dal, stir once, and finish with lemon and cilantro.",
      "Serve with rice.",
    ],
    texturePreferences: ["veg-blended-into-sauces", "no-visible-onions"],
    dietaryTags: ["vegetarian", "gluten-free"],
    containsAllergens: ["dairy"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-mushroom-spinach-orzo",
    title: "One-Pan Mushroom & Spinach Orzo",
    cuisine: "Italian",
    totalMinutes: 25,
    difficulty: "easy",
    heatLevel: "none",
    form: "pasta",
    servesAdults: 4,
    produceUsed: [
      { name: "mushrooms", amount: "12 oz (340 g), sliced" },
      { name: "spinach", amount: "5 oz (140 g)" },
      { name: "garlic", amount: "3 cloves" },
    ],
    otherIngredients: [
      { name: "orzo", amount: "1.5 cups", pantry: true },
      { name: "vegetable stock", amount: "3.5 cups", pantry: true },
      { name: "parmesan", amount: "3/4 cup grated", pantry: false },
      { name: "butter", amount: "2 tbsp", pantry: false },
      { name: "lemon", amount: "1", pantry: false },
      { name: "dried thyme", amount: "1 tsp", pantry: true },
      { name: "olive oil", amount: "2 tbsp", pantry: true },
    ],
    steps: [
      "Brown the mushrooms in the oil over high heat for 6 minutes without stirring much.",
      "Add the garlic and thyme, cook 1 minute, then stir in the orzo and toast it for 1 minute.",
      "Pour in the stock and simmer, stirring often, for 10 minutes until the orzo is tender and the liquid has become a loose sauce.",
      "Stir in the spinach, butter, parmesan and a good squeeze of lemon. It should be creamy, not stiff -- loosen with a splash of water if needed.",
    ],
    texturePreferences: ["no-visible-onions", "no-mixed-textures"],
    dietaryTags: ["vegetarian"],
    containsAllergens: ["dairy", "gluten", "wheat"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-roasted-veg-tacos",
    title: "Roasted Squash & Black Bean Tacos",
    cuisine: "Mexican",
    totalMinutes: 35,
    difficulty: "easy",
    heatLevel: "mild",
    form: "handheld",
    servesAdults: 4,
    produceUsed: [
      { name: "butternut squash", amount: "1.5 lb (680 g), cubed" },
      { name: "cilantro", amount: "3/4 cup" },
      { name: "cabbage", amount: "1/4 head, shredded" },
    ],
    otherIngredients: [
      { name: "corn tortillas", amount: "12", pantry: false },
      { name: "black beans", amount: "1 can (15 oz)", pantry: true },
      { name: "lime", amount: "2", pantry: false },
      { name: "ground cumin", amount: "2 tsp", pantry: true },
      { name: "smoked paprika", amount: "1.5 tsp", pantry: true },
      { name: "olive oil", amount: "3 tbsp", pantry: true },
      { name: "sour cream or avocado", amount: "to taste, to serve", pantry: false },
    ],
    steps: [
      "Heat the oven to 425F (220C). Toss the squash with the oil, cumin, paprika and salt.",
      "Roast 25 minutes, turning once, until caramelised at the edges.",
      "Warm the beans with a splash of water and season.",
      "Toss the cabbage with lime juice and a pinch of salt for a quick crunchy slaw.",
      "Char the tortillas briefly in a dry pan. Fill with squash, beans and slaw, and finish with cilantro and lime.",
    ],
    texturePreferences: ["roasted-not-steamed", "finger-food", "sauce-on-the-side", "no-visible-onions"],
    dietaryTags: ["vegetarian", "vegan-option", "gluten-free"],
    containsAllergens: ["dairy"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-tomato-basil-gnocchi",
    title: "Skillet Gnocchi with Tomatoes & Spinach",
    cuisine: "Italian",
    totalMinutes: 20,
    difficulty: "easy",
    heatLevel: "none",
    form: "pasta",
    servesAdults: 4,
    produceUsed: [
      { name: "cherry tomatoes", amount: "1.5 lb (680 g)" },
      { name: "spinach", amount: "5 oz (140 g)" },
      { name: "basil", amount: "1/2 cup" },
    ],
    otherIngredients: [
      { name: "potato gnocchi", amount: "1.5 lb (680 g)", pantry: false },
      { name: "mozzarella", amount: "8 oz (225 g), torn", pantry: false },
      { name: "garlic", amount: "3 cloves", pantry: true },
      { name: "olive oil", amount: "3 tbsp", pantry: true },
      { name: "salt and pepper", amount: "to taste", pantry: true },
    ],
    steps: [
      "Heat the oil in a large oven-safe skillet over medium-high. Add the gnocchi straight from the package and fry 6 minutes, turning once, until crisp and golden.",
      "Add the tomatoes and garlic and cook 5 minutes, pressing the tomatoes so they burst into a rough sauce.",
      "Stir in the spinach until wilted. Season.",
      "Tear the mozzarella over the top and put the pan under a hot broiler for 3 minutes until melted and blistered.",
      "Scatter with basil and serve from the pan.",
    ],
    texturePreferences: ["no-visible-onions"],
    dietaryTags: ["vegetarian"],
    containsAllergens: ["dairy", "gluten", "wheat"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
  {
    id: "lib-miso-roasted-veg-noodles",
    title: "Miso Roasted Vegetable Noodles",
    cuisine: "Japanese",
    totalMinutes: 35,
    difficulty: "easy",
    heatLevel: "none",
    form: "rice-bowl",
    servesAdults: 4,
    produceUsed: [
      { name: "broccoli", amount: "1 head, in florets" },
      { name: "carrots", amount: "3, in batons" },
      { name: "mushrooms", amount: "8 oz (225 g), halved" },
      { name: "green onion", amount: "4" },
    ],
    otherIngredients: [
      { name: "udon or soba noodles", amount: "14 oz (400 g)", pantry: false },
      { name: "white miso paste", amount: "3 tbsp", pantry: false },
      { name: "soy sauce", amount: "2 tbsp", pantry: true },
      { name: "honey or maple syrup", amount: "1 tbsp", pantry: true },
      { name: "sesame oil", amount: "1 tbsp", pantry: true },
      { name: "neutral oil", amount: "2 tbsp", pantry: true },
      { name: "sesame seeds", amount: "2 tbsp", pantry: true },
    ],
    steps: [
      "Heat the oven to 425F (220C). Whisk the miso, soy, honey, sesame oil and neutral oil into a glaze.",
      "Toss the carrots with a third of the glaze and roast 10 minutes.",
      "Add the broccoli and mushrooms with another third of the glaze and roast 15 minutes more, until the edges are dark and caramelised.",
      "Cook the noodles, drain, and toss with the remaining glaze and a splash of the cooking water.",
      "Pile the roasted vegetables on the noodles. Top with sliced green onion and sesame seeds.",
    ],
    texturePreferences: ["roasted-not-steamed", "no-mixed-textures"],
    dietaryTags: ["vegetarian", "dairy-free"],
    containsAllergens: ["soy", "gluten", "wheat", "sesame"],
    source: "library",
    sourceNote: "Kitchen-tested house recipe",
  },
];

export function getRecipe(id: string): Recipe | undefined {
  return RECIPE_LIBRARY.find((r) => r.id === id);
}
